/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controlClasses.CreateObjectControl;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author annalangstrom
 */
public class CreateObjectGui extends javax.swing.JFrame {
    
    private final AddKeywordsGui addKeys;
    private final AddGenres addGenres;
    private final AddAutArtGui addAutArts;
    /**
     * Creates new form CreateObject
     */
    public CreateObjectGui() {
        super("New item");
        initComponents();
        addKeys = new AddKeywordsGui();
        addGenres = new AddGenres();
        addAutArts = new AddAutArtGui();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel5 = new javax.swing.JLabel();
      txtIsbn2 = new javax.swing.JTextField();
      jDialog1 = new javax.swing.JDialog();
      jDialog2 = new javax.swing.JDialog();
      jFrame1 = new javax.swing.JFrame();
      jLabel8 = new javax.swing.JLabel();
      txtIsbn4 = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      txtTitle = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      txtIsbn = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      txtPubYear = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      txtPCountry = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      cmbCategory = new javax.swing.JComboBox<>();
      jLabel9 = new javax.swing.JLabel();
      txtLocation = new javax.swing.JTextField();
      jLabel10 = new javax.swing.JLabel();
      txtPublisher = new javax.swing.JTextField();
      jLabel11 = new javax.swing.JLabel();
      txtAgeLimit = new javax.swing.JTextField();
      btnAddKeyword = new javax.swing.JButton();
      btnAddGenres = new javax.swing.JButton();
      addAutArt = new javax.swing.JButton();
      btnCancel = new javax.swing.JButton();
      btnSave = new javax.swing.JButton();

      jLabel5.setText("Publish year*");

      javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
      jDialog1.getContentPane().setLayout(jDialog1Layout);
      jDialog1Layout.setHorizontalGroup(
         jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      jDialog1Layout.setVerticalGroup(
         jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
      jDialog2.getContentPane().setLayout(jDialog2Layout);
      jDialog2Layout.setHorizontalGroup(
         jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      jDialog2Layout.setVerticalGroup(
         jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
      jFrame1.getContentPane().setLayout(jFrame1Layout);
      jFrame1Layout.setHorizontalGroup(
         jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      jFrame1Layout.setVerticalGroup(
         jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
      );

      jLabel8.setText("Location*");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
      jLabel1.setText("New item");

      jLabel2.setText("Title*");

      jLabel3.setText("ISBN*");

      jLabel4.setText("Publish year*");

      jLabel6.setText("Location*");

      jLabel7.setText("Category*");

      cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book", "Movie", "Magazine" }));

      jLabel9.setText("Publisher");

      jLabel10.setText("Publisher country");

      jLabel11.setText("Age-limit");

      btnAddKeyword.setText("Add keywords");
      btnAddKeyword.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddKeywordActionPerformed(evt);
         }
      });

      btnAddGenres.setText("Add genres");
      btnAddGenres.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddGenresActionPerformed(evt);
         }
      });

      addAutArt.setText("Add author or artist");
      addAutArt.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            addAutArtActionPerformed(evt);
         }
      });

      btnCancel.setText("Cancel");

      btnSave.setText("Save");
      btnSave.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSaveActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel3)
                           .addComponent(jLabel2)))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(txtPublisher, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                     .addComponent(txtIsbn, javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtPubYear, javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtLocation, javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtPCountry)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(146, 146, 146)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel11)
                     .addComponent(jLabel7))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtAgeLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))
            .addGap(72, 72, 72)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(btnAddKeyword, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
               .addComponent(btnAddGenres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(addAutArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 172, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSave)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnCancel)
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGap(355, 355, 355)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(jLabel1)
            .addGap(61, 61, 61)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtTitle)
               .addComponent(jLabel2)
               .addComponent(btnAddKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3)
               .addComponent(btnAddGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(txtPubYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel4)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(3, 3, 3)
                  .addComponent(addAutArt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(68, 68, 68)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel9)
               .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(16, 16, 16)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel10)
               .addComponent(txtPCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtAgeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel11))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel7))
            .addGap(38, 38, 38)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnCancel)
               .addComponent(btnSave))
            .addContainerGap())
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

    private void btnAddKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKeywordActionPerformed
        addKeys.setVisible(true);
    }//GEN-LAST:event_btnAddKeywordActionPerformed

    private void btnAddGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGenresActionPerformed
        addGenres.setVisible(true);
    }//GEN-LAST:event_btnAddGenresActionPerformed

    private void addAutArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAutArtActionPerformed
        addAutArts.setVisible(true);
    }//GEN-LAST:event_addAutArtActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFrame frame = new JFrame();
        try {
            // TODO add your handling code here:
            CreateObjectControl control = new CreateObjectControl();
            if(cmbCategory.getSelectedItem().equals("Book"))
                control.addBookToDB(txtIsbn.getText(), txtPublisher.getText(), txtTitle.getText(),
                        Integer.parseInt(txtPubYear.getText()), txtLocation.getText(), addKeys.getThings(),
                        addGenres.getThings(), addAutArts.getThings());
            /*String isbn, String publisher, String title, 
            int publishYear, String location, ArrayList<String> keywords, 
            ArrayList<String> genres, ArrayList<String> authorArtist*/
            else if(cmbCategory.getSelectedItem().equals("Movie"))
                control.addMovieToDB(Integer.parseInt(txtAgeLimit.getText()), txtPCountry.getText(), 
                        txtTitle.getText(), Integer.parseInt(txtPubYear.getText()), txtLocation.getText(), 
                        addKeys.getThings(), addGenres.getThings(), addAutArts.getThings());
            /*int ageLimit, String pCountry, String title, 
            int publishYear, String location, ArrayList<String> keywords, 
            ArrayList<String> genres, ArrayList<String> authorArtist*/
           
            else if(cmbCategory.getSelectedItem().equals("Magazine"))
                control.addMagazineToDB(txtPublisher.getText(), txtTitle.getText(), 
                        Integer.parseInt(txtPubYear.getText()), txtLocation.getText(), 
                        addKeys.getThings(), addGenres.getThings(), addAutArts.getThings());
            /*String publisher, String title, int publishYear, 
            String location, ArrayList<String> keywords, ArrayList<String> genres, 
            ArrayList<String> authorArtist*/
            control.confirmSaving();
            
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(frame, "Something went wrong, " + ex.getMessage());
            Logger.getLogger(CreateObjectGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CreateObjectGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CreateObjectGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CreateObjectGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CreateObjectGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CreateObjectGui().setVisible(true);
//            }
//        });
//    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton addAutArt;
   private javax.swing.JButton btnAddGenres;
   private javax.swing.JButton btnAddKeyword;
   private javax.swing.JButton btnCancel;
   private javax.swing.JButton btnSave;
   private javax.swing.JComboBox<String> cmbCategory;
   private javax.swing.JDialog jDialog1;
   private javax.swing.JDialog jDialog2;
   private javax.swing.JFrame jFrame1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JTextField txtAgeLimit;
   private javax.swing.JTextField txtIsbn;
   private javax.swing.JTextField txtIsbn2;
   private javax.swing.JTextField txtIsbn4;
   private javax.swing.JTextField txtLocation;
   private javax.swing.JTextField txtPCountry;
   private javax.swing.JTextField txtPubYear;
   private javax.swing.JTextField txtPublisher;
   private javax.swing.JTextField txtTitle;
   // End of variables declaration//GEN-END:variables
}
