/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Caroline
 */
public class UpdatePersonalInfoGui extends javax.swing.JFrame {

   /**
    * Creates new form UpdatePersonalInfoGui
    */
   public UpdatePersonalInfoGui() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jFrame1 = new javax.swing.JFrame();
      btnHomePage = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      btnSignOut = new javax.swing.JButton();
      btnUpdatePersonalData = new javax.swing.JButton();
      btnCancle = new javax.swing.JButton();
      jLabel2 = new javax.swing.JLabel();
      btnSignOut1 = new javax.swing.JButton();
      btnSave = new javax.swing.JButton();
      checkBoxStudent = new javax.swing.JCheckBox();
      checkBoxReasearcher = new javax.swing.JCheckBox();
      checkBoxOtherUni = new javax.swing.JCheckBox();
      checkBoxNon = new javax.swing.JCheckBox();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      txtStreet = new javax.swing.JTextField();
      txtEmail = new javax.swing.JTextField();
      txtPostcode1 = new javax.swing.JTextField();
      txtCity = new javax.swing.JTextField();
      txtTelephone = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      txtNewPassword = new javax.swing.JTextField();
      txtRepeatNewPassword = new javax.swing.JTextField();
      txtOldPassword = new javax.swing.JTextField();

      btnHomePage.setText("Home Page");
      btnHomePage.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnHomePageActionPerformed(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
      jLabel1.setText("My page");

      btnSignOut.setText("Sign out");

      btnUpdatePersonalData.setText("Update Personal Data");
      btnUpdatePersonalData.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnUpdatePersonalDataActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
      jFrame1.getContentPane().setLayout(jFrame1Layout);
      jFrame1Layout.setHorizontalGroup(
         jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
         .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jFrame1Layout.createSequentialGroup()
                     .addGap(239, 239, 239)
                     .addComponent(jLabel1))
                  .addGroup(jFrame1Layout.createSequentialGroup()
                     .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                           .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(btnSignOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(btnHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                           .addGap(137, 137, 137))
                        .addGroup(jFrame1Layout.createSequentialGroup()
                           .addComponent(btnUpdatePersonalData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                     .addGap(62, 62, 62)))
               .addContainerGap()))
      );
      jFrame1Layout.setVerticalGroup(
         jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 300, Short.MAX_VALUE)
         .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel1)
                  .addComponent(btnHomePage))
               .addGap(224, 224, 224)
               .addGroup(jFrame1Layout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addComponent(btnUpdatePersonalData)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(btnSignOut))
               .addContainerGap()))
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      btnCancle.setText("Cancel");
      btnCancle.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancleActionPerformed(evt);
         }
      });

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
      jLabel2.setText("Update Personal Information");

      btnSignOut1.setText("Sign out");

      btnSave.setText("Save");
      btnSave.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSaveActionPerformed(evt);
         }
      });

      checkBoxStudent.setText("Student");
      checkBoxStudent.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkBoxStudentActionPerformed(evt);
         }
      });

      checkBoxReasearcher.setText("Reasearcher");

      checkBoxOtherUni.setText("Other University Employee");

      checkBoxNon.setText("Non of the above");

      jLabel3.setText("Address:");

      jLabel4.setText("Telephone:");

      jLabel5.setText("Email:");

      txtStreet.setForeground(new java.awt.Color(102, 102, 102));
      txtStreet.setText("New street");

      txtEmail.setForeground(new java.awt.Color(102, 102, 102));
      txtEmail.setText("New e-mail");

      txtPostcode1.setForeground(new java.awt.Color(102, 102, 102));
      txtPostcode1.setText("New postcode");

      txtCity.setForeground(new java.awt.Color(102, 102, 102));
      txtCity.setText("New city");

      txtTelephone.setForeground(new java.awt.Color(102, 102, 102));
      txtTelephone.setText("New telephone");

      jLabel6.setText("Pasword:");

      txtNewPassword.setForeground(new java.awt.Color(102, 102, 102));
      txtNewPassword.setText("New password");

      txtRepeatNewPassword.setForeground(new java.awt.Color(102, 102, 102));
      txtRepeatNewPassword.setText("Repeat New Password");

      txtOldPassword.setForeground(new java.awt.Color(102, 102, 102));
      txtOldPassword.setText("Old password");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(171, 171, 171)
                  .addComponent(jLabel2))
               .addGroup(layout.createSequentialGroup()
                  .addGap(523, 523, 523)
                  .addComponent(checkBoxNon))
               .addGroup(layout.createSequentialGroup()
                  .addGap(39, 39, 39)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel3)
                     .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(91, 91, 91)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(checkBoxStudent))
                     .addComponent(jLabel4)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(39, 39, 39)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtPostcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(btnSignOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel6)
                           .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(txtRepeatNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(77, 77, 77)
                              .addComponent(checkBoxOtherUni))
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel5)
                              .addGap(199, 199, 199)
                              .addComponent(checkBoxReasearcher))))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))))
            .addGap(18, 18, 18))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jLabel2)
            .addGap(37, 37, 37)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel3)
               .addComponent(jLabel4))
            .addGap(7, 7, 7)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(checkBoxStudent)
               .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(13, 13, 13)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txtPostcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(checkBoxReasearcher))
                  .addGap(13, 13, 13))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jLabel5)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(checkBoxOtherUni)
               .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addComponent(checkBoxNon)
            .addGap(43, 43, 43)
            .addComponent(jLabel6)
            .addGap(7, 7, 7)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnSave))
            .addGap(13, 13, 13)
            .addComponent(txtRepeatNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13)
            .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnSignOut1)
               .addComponent(btnCancle))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePageActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnHomePageActionPerformed

   private void btnUpdatePersonalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePersonalDataActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnUpdatePersonalDataActionPerformed

   private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnCancleActionPerformed

   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_btnSaveActionPerformed

   private void checkBoxStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxStudentActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_checkBoxStudentActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(UpdatePersonalInfoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(UpdatePersonalInfoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(UpdatePersonalInfoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(UpdatePersonalInfoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new UpdatePersonalInfoGui().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCancle;
   private javax.swing.JButton btnHomePage;
   private javax.swing.JButton btnSave;
   private javax.swing.JButton btnSignOut;
   private javax.swing.JButton btnSignOut1;
   private javax.swing.JButton btnUpdatePersonalData;
   private javax.swing.JCheckBox checkBoxNon;
   private javax.swing.JCheckBox checkBoxOtherUni;
   private javax.swing.JCheckBox checkBoxReasearcher;
   private javax.swing.JCheckBox checkBoxStudent;
   private javax.swing.JFrame jFrame1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JTextField txtCity;
   private javax.swing.JTextField txtEmail;
   private javax.swing.JTextField txtNewPassword;
   private javax.swing.JTextField txtOldPassword;
   private javax.swing.JTextField txtPostcode1;
   private javax.swing.JTextField txtRepeatNewPassword;
   private javax.swing.JTextField txtStreet;
   private javax.swing.JTextField txtTelephone;
   // End of variables declaration//GEN-END:variables
}
